

spring.application.name=ApiGateway
server.port=8085

##spring.application.name=api-gateway
##server.port=9090
#
## Gateway Discovery Settings
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#
## Eureka Discovery
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#server.error.include-stacktrace:never


##routes configuration
spring.cloud.gateway.routes[0].id=flight-search-service
spring.cloud.gateway.routes[0].uri=lb://flight-search-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/flights/**

spring.cloud.gateway.routes[1].id=fare-service
spring.cloud.gateway.routes[1].uri=lb://fare-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/fares/**

spring.cloud.gateway.routes[2].id=booking-service
##spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].uri=lb://booking-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**

spring.cloud.gateway.routes[3].id=checkin-service
##spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].uri=lb://checkin-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/checkin/**

spring.cloud.gateway.routes[4].id=SpringSecurity
spring.cloud.gateway.routes[4].uri=lb://SpringSecurity
spring.cloud.gateway.routes[4].predicates[0]=Path=/SpringSecurity/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## Gateway Configuration for Service Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



